### PR TITLE
Create nx.js

### PR DESCRIPTION
**Pull request by ghost**
## Requirements

Proj.at reserves the right to review your domain name for approval.

- [X] I provided a record file based on the template.
- [X] I have put the record file in the `domains/proj.sbs` folder.
- [X] I promised that I will not use the domain for any illegal activities.
- [X] I promised that this domain is for open-source projects only.
- [X] The record of the subdomain works.
- [X] I have read the [Terms of Service](https://github.com/proj-at/subdomains/wiki/term-of-service).

### CODE REVIEW

**Comment by jadfoq** [comment]
hiii @ocoke

**Comment by ocoke** [comment]
thank you for reopening this again, enjoy your `proj.sbs` domain

**Comment by ocoke** [comment]
actually, we don't suggest `NS` record, and we're not sure that works. Can you change it to `A/AAAA/CNAME`?

**Comment by jadfoq** [comment]
> actually, we don't suggest `NS` record, and we're not sure that works. Can you change it to `A/AAAA/CNAME`?

It's strange, why do you support this type of DNS records? I want to delete my _github_ account because _github_ is proprietary and evil

**Pull request closed without merging**
