### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
## Requirements

Proj.at reserves the right to review your domain name for approval.

Notes: `proj.at` currently doesn't accept subdomain requests. Please use `proj.sbs`.

- [ ] I provided a record file based on the template.
- [ ] I have put the record file in the `domains/proj.sbs` folder.
- [ ] I promised that I will not use the domain for any illegal activities.
- [ ] I promised that this domain is for open-source projects only.
- [ ] The record of the subdomain works.
- [ ] I have read the [Terms of Service](https://github.com/proj-at/subdomains/wiki/term-of-service).

### CODE REVIEW

**Comment by ghost** [comment]
ok @ocoke ive recreated

**Comment by ghost** [comment]
i’ll update most CNAMEs to A soon. long story short it’s complicated

**Comment by ocoke** [comment]
I'm so sorry but some subdomain names are too common like `api`, `app`, `cdn`. We can't give u these subdomains.
if you really need it, please try to make it in the format of wildcards.

**Comment by ghost** [comment]
i tried... ok lemme fix that rq

**Comment by ghost** [comment]
ok @ocoke fixed it

**Comment by ghost** [comment]
do you know when you’ll accept proj.at domains btw

**Comment by ocoke** [comment]
great!!

> do you know when you’ll accept proj.at domains btw

**Comment by ghost** [comment]
should be ready for merge if there’s not anything else

~~this should probably be merged as one commit to keep it readable~~

**Pull request merged**
