### PR TITLE
Create Rederator.js

### PR DESCRIPTION
**Pull request by CarsonDay11**
## Requirements

Proj.at reserves the right to review your domain name for approval.

- [x] I provided a record file based on the template.
- [x] I have put the record file in the `domains/proj.sbs` folder.
- [x] I promised that I will not use the domain for any illegal activities.
- [x] I promised that this domain is for open-source projects only.
- [x] The record of the subdomain works.
- [x] I have read the [Terms of Service](https://github.com/proj-at/subdomains/wiki/term-of-service).

### CODE REVIEW

**Comment by CarsonDay11** [comment]
The Github repository is https://github.com/CarsonDay11/rederator

**Comment by ocoke** [comment]
only txt record? by the way we're not sure if that `proj.sbs` could be used in Vercel

**Comment by CarsonDay11** [comment]
> only txt record? by the way we're not sure if that `proj.sbs` could be used in Vercel

It says that you can remove the TXT record after... what would some good alternate static hosting providers be?

**Comment by ocoke** [comment]
Seems that the file only includes a TXT record, I think there should be a CNAME record, otherwise, the site can't be reached.
Actually, we have not tested our domain in Vercel, you can try it, and if it can be used, welcome to share :)
Thank you very much.

**Pull request closed without merging**
